import io
import zipfile
import json
from typing import Dict, Any

def generate_export_zip(website_data: Dict[str, Any]) -> io.BytesIO:
    page_tree = website_data.get("page_tree", {})
    brand_name = page_tree.get("brand_name", website_data.get("title", "My Website"))
    logo_url = website_data.get("logo_url") or page_tree.get("navbar", {}).get("logo_url")
    tagline = page_tree.get("tagline", "Built with BuildMyWebsiteAI")
    colors = page_tree.get("colors", {})
    website_type = page_tree.get("website_type", "single")
    selected_pages = page_tree.get("selected_pages", ["Home", "About Us", "Services", "Contact Us"])
    pages_dict = page_tree.get("pages", {})

    bg = colors.get("bg", "#f8fafc")
    surface = colors.get("surface", "#ffffff")
    primary = colors.get("primary", "#06b6d4")
    secondary = colors.get("secondary", "#ec4899")
    text_color = colors.get("text", "#0f172a")
    accent = colors.get("accent", "#38bdf8")

    navbar = page_tree.get("navbar", {})
    hero = page_tree.get("hero", {})
    features = page_tree.get("features", {})
    testimonials = page_tree.get("testimonials", {})
    faq = page_tree.get("faq", {})
    cta = page_tree.get("cta", {})
    footer = page_tree.get("footer", {})

    css_content = f"""/* Generated by BuildMyWebsiteAI Studio - https://buildmywebsiteai.ai */
:root {{
  --bg-color: {bg};
  --surface-color: {surface};
  --primary-color: {primary};
  --secondary-color: {secondary};
  --text-color: {text_color};
  --accent-color: {accent};
  --font-family: 'Inter', system-ui, -apple-system, sans-serif;
}}

* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{ background-color: var(--bg-color); color: var(--text-color); font-family: var(--font-family); line-height: 1.6; overflow-x: hidden; }}
a {{ color: inherit; text-decoration: none; }}
.container {{ max-width: 1200px; margin: 0 auto; padding: 0 20px; }}

header {{ position: fixed; top: 0; left: 0; right: 0; z-index: 100; background: rgba(255, 255, 255, 0.9); backdrop-filter: blur(16px); border-bottom: 1px solid rgba(0, 0, 0, 0.08); padding: 16px 0; }}
.nav-wrap {{ display: flex; justify-content: space-between; align-items: center; }}
.logo-wrap {{ display: flex; align-items: center; gap: 10px; }}
.logo-img {{ height: 34px; width: 34px; object-fit: contain; border-radius: 8px; }}
.logo {{ font-size: 24px; font-weight: 800; color: var(--primary-color); }}
.nav-links {{ display: flex; gap: 24px; list-style: none; }}
.nav-links a:hover {{ color: var(--accent-color); transition: color 0.2s ease; }}
.btn-primary {{ background: linear-gradient(135deg, var(--primary-color), var(--secondary-color)); color: #fff; padding: 10px 24px; border-radius: 9999px; font-weight: 600; display: inline-block; border: none; cursor: pointer; box-shadow: 0 10px 25px -5px rgba(6, 182, 212, 0.4); }}

.hero-section {{ padding: 140px 0 80px; text-align: center; }}
.badge {{ display: inline-block; background: rgba(6, 182, 212, 0.1); border: 1px solid var(--primary-color); color: var(--primary-color); padding: 6px 16px; border-radius: 9999px; font-size: 13px; font-weight: 600; margin-bottom: 20px; }}
.hero-title {{ font-size: 48px; font-weight: 900; margin-bottom: 20px; line-height: 1.15; color: var(--text-color); }}
.hero-subtitle {{ font-size: 18px; color: rgba(15, 23, 42, 0.7); max-width: 700px; margin: 0 auto 30px; }}
.hero-img {{ width: 100%; max-width: 900px; border-radius: 16px; margin-top: 30px; border: 1px solid rgba(0, 0, 0, 0.1); box-shadow: 0 20px 40px -10px rgba(0, 0, 0, 0.15); }}

.features-section {{ padding: 80px 0; background: var(--surface-color); }}
.section-header {{ text-align: center; margin-bottom: 50px; }}
.features-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 24px; }}
.feature-card {{ background: rgba(248, 250, 252, 0.8); border: 1px solid rgba(0, 0, 0, 0.06); border-radius: 16px; padding: 24px; }}

@media (max-width: 768px) {{
  .container {{ padding: 0 16px; }}
  .nav-links {{ display: none; }}
  .hero-section {{ padding: 110px 0 50px; }}
  .hero-title {{ font-size: 28px !important; }}
  .hero-subtitle {{ font-size: 15px !important; }}
  .features-grid {{ grid-template-columns: 1fr !important; }}
}}
"""

    def build_page_html(page_name: str, p_data: Dict[str, Any]) -> str:
        p_hero = p_data.get("hero", hero)
        p_features = p_data.get("features", features)
        
        nav_items_html = "".join([f'<li><a href="{link.get("href")}">{link.get("label")}</a></li>' for link in navbar.get("links", [])])
        
        features_items_html = "".join([
            f"""<div class="feature-card">
                  <h3 style="font-size: 18px; margin-bottom: 8px; color: var(--primary-color);">{item.get('title')}</h3>
                  <p style="color: rgba(15,23,42,0.7); font-size: 14px;">{item.get('description')}</p>
                </div>"""
            for item in p_features.get("items", [])
        ])

        logo_img_html = f'<img src="{logo_url}" alt="Logo" class="logo-img">' if logo_url else ''

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{page_name} - {brand_name}</title>
  <link rel="stylesheet" href="styles.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap" rel="stylesheet">
</head>
<body>

  <!-- Navbar -->
  <header>
    <div class="container nav-wrap">
      <div class="logo-wrap">
        {logo_img_html}
        <span class="logo">{brand_name}</span>
      </div>
      <ul class="nav-links">
        {nav_items_html}
      </ul>
      <a href="contact_us.html" class="btn-primary">{navbar.get('cta_button', 'Get Started')}</a>
    </div>
  </header>

  <!-- Hero Section -->
  <section class="hero-section">
    <div class="container">
      <div class="badge">{p_hero.get('badge', '⚡ Powered by BuildMyWebsiteAI')}</div>
      <h1 class="hero-title">{p_hero.get('headline', brand_name)}</h1>
      <p class="hero-subtitle">{p_hero.get('subheadline', tagline)}</p>
      {f'<img src="{p_hero.get("hero_image")}" alt="Hero Banner" class="hero-img">' if p_hero.get("hero_image") else ''}
    </div>
  </section>

  <!-- Features Section -->
  <section class="features-section">
    <div class="container">
      <div class="section-header">
        <div class="badge">{p_features.get('section_badge', 'Capabilities')}</div>
        <h2 style="font-size: 32px; font-weight: 800; color: var(--text-color);">{p_features.get('section_title', 'Key Features')}</h2>
      </div>
      <div class="features-grid">
        {features_items_html}
      </div>
    </div>
  </section>

  <footer style="padding: 40px 0; border-top: 1px solid rgba(0,0,0,0.08); text-align: center; color: rgba(15,23,42,0.6); font-size: 14px;">
    <div class="container">
      <p>&copy; 2026 {brand_name}. All rights reserved. Powered by BuildMyWebsiteAI.</p>
    </div>
  </footer>

</body>
</html>"""

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        zip_file.writestr("styles.css", css_content)
        zip_file.writestr("index.html", build_page_html("Home", pages_dict.get("Home", {})))
        
        for page_name in selected_pages:
            if page_name != "Home":
                filename = f"{page_name.lower().replace(' ', '_')}.html"
                p_content = build_page_html(page_name, pages_dict.get(page_name, {}))
                zip_file.writestr(filename, p_content)

    zip_buffer.seek(0)
    return zip_buffer
