import io
import zipfile
import json
from typing import Dict, Any

def generate_export_zip(website_data: Dict[str, Any]) -> io.BytesIO:
    page_tree = website_data.get("page_tree", {})
    brand_name = page_tree.get("brand_name", website_data.get("title", "My Website"))
    logo_url = website_data.get("logo_url") or page_tree.get("navbar", {}).get("logo_url")
    tagline = page_tree.get("tagline", "Built with BuildMyWebsiteAI")
    colors = page_tree.get("colors", {})
    website_type = page_tree.get("website_type", "single")
    selected_pages = page_tree.get("selected_pages", ["Home", "About Us", "Services", "Contact Us"])
    pages_dict = page_tree.get("pages", {})

    bg = colors.get("bg", "#f8fafc")
    surface = colors.get("surface", "#ffffff")
    primary = colors.get("primary", "#06b6d4")
    secondary = colors.get("secondary", "#ec4899")
    text_color = colors.get("text", "#0f172a")
    accent = colors.get("accent", "#38bdf8")

    navbar = page_tree.get("navbar", {})
    hero = page_tree.get("hero", {})
    about = page_tree.get("about", {})
    services = page_tree.get("services", {})
    features = page_tree.get("features", {})
    faq = page_tree.get("faq", {})
    testimonials = page_tree.get("testimonials", {})
    cta = page_tree.get("cta", {})
    contact = page_tree.get("contact", {})
    footer = page_tree.get("footer", {})

    css_content = f"""/* Generated by BuildMyWebsiteAI Studio - https://buildmywebsiteai.ai */
:root {{
  --bg-color: {bg};
  --surface-color: {surface};
  --primary-color: {primary};
  --secondary-color: {secondary};
  --text-color: {text_color};
  --accent-color: {accent};
  --font-family: 'Inter', system-ui, -apple-system, sans-serif;
}}

* {{ box-sizing: border-box; margin: 0; padding: 0; }}
html {{ scroll-behavior: smooth; }}
body {{ background-color: var(--bg-color); color: var(--text-color); font-family: var(--font-family); line-height: 1.6; overflow-x: hidden; }}
a {{ color: inherit; text-decoration: none; }}
.container {{ max-width: 1200px; margin: 0 auto; padding: 0 20px; }}

header {{ position: fixed; top: 0; left: 0; right: 0; z-index: 100; background: rgba(255, 255, 255, 0.95); backdrop-filter: blur(16px); border-bottom: 1px solid rgba(0, 0, 0, 0.08); padding: 16px 0; }}
.nav-wrap {{ display: flex; justify-content: space-between; align-items: center; }}
.logo-wrap {{ display: flex; align-items: center; gap: 10px; }}
.logo-img {{ height: 34px; width: 34px; object-fit: contain; border-radius: 8px; }}
.logo {{ font-size: 24px; font-weight: 800; color: var(--primary-color); }}
.nav-links {{ display: flex; gap: 24px; list-style: none; }}
.nav-links a:hover {{ color: var(--accent-color); transition: color 0.2s ease; }}
.btn-primary {{ background: linear-gradient(135deg, var(--primary-color), var(--secondary-color)); color: #fff; padding: 10px 24px; border-radius: 9999px; font-weight: 600; display: inline-block; border: none; cursor: pointer; box-shadow: 0 10px 25px -5px rgba(6, 182, 212, 0.4); transition: transform 0.2s ease; }}
.btn-primary:hover {{ transform: scale(1.04); }}

.hero-section {{ padding: 140px 0 80px; text-align: center; scroll-margin-top: 80px; }}
.badge {{ display: inline-block; background: rgba(6, 182, 212, 0.1); border: 1px solid var(--primary-color); color: var(--primary-color); padding: 6px 16px; border-radius: 9999px; font-size: 13px; font-weight: 600; margin-bottom: 20px; }}
.hero-title {{ font-size: 48px; font-weight: 900; margin-bottom: 20px; line-height: 1.15; color: var(--text-color); }}
.hero-subtitle {{ font-size: 18px; color: rgba(15, 23, 42, 0.7); max-width: 700px; margin: 0 auto 30px; }}
.hero-img {{ width: 100%; max-width: 900px; border-radius: 16px; margin-top: 30px; border: 1px solid rgba(0, 0, 0, 0.1); box-shadow: 0 20px 40px -10px rgba(0, 0, 0, 0.15); }}

.section {{ padding: 80px 0; scroll-margin-top: 80px; }}
.section-alt {{ padding: 80px 0; background: var(--surface-color); scroll-margin-top: 80px; }}
.section-header {{ text-align: center; margin-bottom: 50px; }}
.grid-3 {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 24px; }}
.card {{ background: rgba(255, 255, 255, 0.9); border: 1px solid rgba(0, 0, 0, 0.08); border-radius: 16px; padding: 28px; transition: transform 0.3s ease, box-shadow 0.3s ease; }}
.card:hover {{ transform: translateY(-6px); box-shadow: 0 15px 30px rgba(0,0,0,0.08); }}

footer {{ background: #090d16; color: #94a3b8; padding: 50px 0 20px; text-align: center; font-size: 14px; }}
footer a {{ color: var(--accent-color); }}

@media (max-width: 768px) {{
  .container {{ padding: 0 16px; }}
  .nav-links {{ display: none; }}
  .hero-section {{ padding: 110px 0 50px; }}
  .hero-title {{ font-size: 28px !important; }}
  .hero-subtitle {{ font-size: 15px !important; }}
  .grid-3 {{ grid-template-columns: 1fr !important; }}
}}
"""

    def build_page_html(page_name: str, p_data: Dict[str, Any]) -> str:
        p_hero = p_data.get("hero", hero)
        p_about = p_data.get("about") if website_type == "multi" else page_tree.get("about", about)
        p_services = p_data.get("services") if website_type == "multi" else page_tree.get("services", services)
        p_features = p_data.get("features") if website_type == "multi" else page_tree.get("features", features)
        p_faq = p_data.get("faq") if website_type == "multi" else page_tree.get("faq", faq)
        p_testimonials = p_data.get("testimonials") if website_type == "multi" else page_tree.get("testimonials", testimonials)
        p_cta = p_data.get("cta") if website_type == "multi" else page_tree.get("cta", cta)
        p_footer = p_data.get("footer", footer)

        nav_items_html = "".join([f'<li><a href="{link.get("href")}">{link.get("label")}</a></li>' for link in navbar.get("links", [])])
        logo_img_html = f'<img src="{logo_url}" alt="Logo" class="logo-img">' if logo_url else ''

        # Build Section HTML snippets with AOS Scroll Animations
        hero_html = f"""
  <section id="home" class="hero-section" data-aos="fade-down">
    <div class="container">
      {f'<span class="badge">{p_hero.get("badge")}</span>' if p_hero.get("badge") else ''}
      <h1 class="hero-title">{p_hero.get("headline", brand_name)}</h1>
      <p class="hero-subtitle">{p_hero.get("subheadline", "")}</p>
      <div>
        <a href="#services" class="btn-primary">{p_hero.get("primary_cta", "Explore Services")}</a>
      </div>
      {f'<img src="{p_hero.get("hero_image")}" alt="Hero" class="hero-img" data-aos="zoom-in" data-aos-delay="200">' if p_hero.get("hero_image") else ''}
    </div>
  </section>"""

        about_html = ""
        if p_about and p_about.get("paragraphs"):
            paragraphs_html = "".join([f'<p style="margin-bottom: 12px; font-size: 15px;">{p}</p>' for p in p_about.get("paragraphs", [])])
            about_html = f"""
  <section id="about" class="section-alt" data-aos="fade-up">
    <div class="container">
      <div class="section-header">
        <span class="badge">{p_about.get("section_badge", "Our Story")}</span>
        <h2 style="font-size: 32px; font-weight: 900;">{p_about.get("section_title", "About Us")}</h2>
      </div>
      <div style="max-width: 800px; margin: 0 auto; text-align: center;">
        {paragraphs_html}
      </div>
    </div>
  </section>"""

        services_html = ""
        if p_services and p_services.get("items"):
            items_html = "".join([
                f"""<div class="card" data-aos="fade-up" data-aos-delay="{idx * 100}">
                      <h3 style="font-size: 18px; margin-bottom: 8px; color: var(--secondary-color);">{item.get('title')}</h3>
                      <p style="color: rgba(15,23,42,0.7); font-size: 14px;">{item.get('description')}</p>
                    </div>"""
                for idx, item in enumerate(p_services.get("items", []))
            ])
            services_html = f"""
  <section id="services" class="section">
    <div class="container">
      <div class="section-header" data-aos="fade-up">
        <span class="badge">{p_services.get("section_badge", "Offerings")}</span>
        <h2 style="font-size: 32px; font-weight: 900;">{p_services.get("section_title", "Our Services")}</h2>
        <p style="color: rgba(15,23,42,0.7);">{p_services.get("section_subtitle", "")}</p>
      </div>
      <div class="grid-3">
        {items_html}
      </div>
    </div>
  </section>"""

        features_html = ""
        if p_features and p_features.get("items"):
            items_html = "".join([
                f"""<div class="card" data-aos="fade-up" data-aos-delay="{idx * 100}">
                      <h3 style="font-size: 18px; margin-bottom: 8px; color: var(--primary-color);">{item.get('title')}</h3>
                      <p style="color: rgba(15,23,42,0.7); font-size: 14px;">{item.get('description')}</p>
                    </div>"""
                for idx, item in enumerate(p_features.get("items", []))
            ])
            features_html = f"""
  <section id="features" class="section-alt">
    <div class="container">
      <div class="section-header" data-aos="fade-up">
        <span class="badge">{p_features.get("section_badge", "Capabilities")}</span>
        <h2 style="font-size: 32px; font-weight: 900;">{p_features.get("section_title", "Why Choose Us")}</h2>
        <p style="color: rgba(15,23,42,0.7);">{p_features.get("section_subtitle", "")}</p>
      </div>
      <div class="grid-3">
        {items_html}
      </div>
    </div>
  </section>"""

        testimonials_html = ""
        if p_testimonials and p_testimonials.get("items"):
            items_html = "".join([
                f"""<div class="card" data-aos="fade-up" data-aos-delay="{idx * 100}">
                      <p style="font-style: italic; margin-bottom: 12px; font-size: 14px;">"{item.get('quote')}"</p>
                      <strong style="color: var(--primary-color);">{item.get('name')}</strong> - <span style="font-size: 12px; opacity: 0.8;">{item.get('role')}</span>
                    </div>"""
                for idx, item in enumerate(p_testimonials.get("items", []))
            ])
            testimonials_html = f"""
  <section class="section">
    <div class="container">
      <div class="section-header" data-aos="fade-up">
        <h2 style="font-size: 32px; font-weight: 900;">{p_testimonials.get("section_title", "What Clients Say")}</h2>
        <p style="color: rgba(15,23,42,0.7);">{p_testimonials.get("section_subtitle", "")}</p>
      </div>
      <div class="grid-3">
        {items_html}
      </div>
    </div>
  </section>"""

        faq_html = ""
        if p_faq and p_faq.get("items"):
            items_html = "".join([
                f"""<div class="card" style="margin-bottom: 16px;" data-aos="fade-up">
                      <h4 style="font-size: 16px; font-weight: 700; margin-bottom: 6px;">{item.get('question')}</h4>
                      <p style="color: rgba(15,23,42,0.7); font-size: 14px;">{item.get('answer')}</p>
                    </div>"""
                for item in p_faq.get("items", [])
            ])
            faq_html = f"""
  <section id="faq" class="section-alt">
    <div class="container" style="max-width: 800px;">
      <div class="section-header" data-aos="fade-up">
        <h2 style="font-size: 32px; font-weight: 900;">{p_faq.get("section_title", "Frequently Asked Questions")}</h2>
      </div>
      <div>
        {items_html}
      </div>
    </div>
  </section>"""

        cta_html = ""
        if p_cta:
            cta_html = f"""
  <section id="contact" class="section" style="text-align: center; background: linear-gradient(135deg, rgba(6,182,212,0.1), rgba(236,72,153,0.1));" data-aos="zoom-in">
    <div class="container" style="max-width: 600px;">
      <h2 style="font-size: 32px; font-weight: 900; margin-bottom: 12px;">{p_cta.get("headline", "Contact Us")}</h2>
      <p style="color: rgba(15,23,42,0.7); margin-bottom: 24px;">{p_cta.get("subheadline", "")}</p>
      <a href="mailto:{p_footer.get('contact_email', 'contact@website.com')}" class="btn-primary">{p_cta.get("button_text", "Send Us a Message")}</a>
    </div>
  </section>"""

        footer_html = f"""
  <footer>
    <div class="container">
      <h3 style="color: #fff; margin-bottom: 8px;">{brand_name}</h3>
      <p style="margin-bottom: 16px;">{p_footer.get("description", "")}</p>
      <p style="font-size: 12px; opacity: 0.7;">{p_footer.get("copyright", "")} | {p_footer.get("credit", "BuildMyWebsiteAI")}</p>
    </div>
  </footer>"""

        # Assemble page content strictly according to page_name
        body_content = hero_html
        if website_type == "single":
            body_content += about_html + services_html + features_html + testimonials_html + faq_html + cta_html
        else:
            if page_name == "Home":
                body_content += features_html + cta_html
            elif page_name == "About Us":
                body_content += about_html
            elif page_name == "Services":
                body_content += services_html
            elif page_name == "Contact Us":
                body_content += cta_html
            else:
                body_content += about_html + services_html

        body_content += footer_html

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{page_name} - {brand_name}</title>
  <link rel="stylesheet" href="styles.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap" rel="stylesheet">
  <!-- AOS Animation Library CDN -->
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
</head>
<body>

  <!-- Navbar -->
  <header>
    <div class="container nav-wrap">
      <div class="logo-wrap">
        {logo_img_html}
        <span class="logo">{brand_name}</span>
      </div>
      <ul class="nav-links">
        {nav_items_html}
      </ul>
      <a href="#contact" class="btn-primary">{navbar.get('cta_button', 'Get In Touch')}</a>
    </div>
  </header>

  {body_content}

  <!-- AOS Scroll Animation Script -->
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init({{
      duration: 800,
      once: true,
      easing: 'ease-in-out'
    }});
  </script>

</body>
</html>
"""

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
        zip_file.writestr("styles.css", css_content)
        
        if website_type == "multi" and pages_dict:
            for p_name, p_data in pages_dict.items():
                filename = "index.html" if p_name == "Home" else f"{p_name.lower().replace(' ', '_')}.html"
                html_content = build_page_html(p_name, p_data)
                zip_file.writestr(filename, html_content)
        else:
            html_content = build_page_html("Home", page_tree)
            zip_file.writestr("index.html", html_content)
            
    zip_buffer.seek(0)
    return zip_buffer
