import io
import zipfile
import json
from typing import Dict, Any

def generate_export_zip(website_data: Dict[str, Any]) -> io.BytesIO:
    page_tree = website_data.get("page_tree", {})
    brand_name = page_tree.get("brand_name", website_data.get("title", "My Website"))
    logo_url = website_data.get("logo_url") or page_tree.get("navbar", {}).get("logo_url")
    tagline = page_tree.get("tagline", "Built with BuildMyWebsiteAI")
    colors = page_tree.get("colors", {})
    website_type = page_tree.get("website_type", "single")
    selected_pages = page_tree.get("selected_pages", ["Home", "About Us", "Services", "Contact Us"])
    pages_dict = page_tree.get("pages", {})

    bg = colors.get("bg", "#f8fafc")
    surface = colors.get("surface", "#ffffff")
    primary = colors.get("primary", "#06b6d4")
    secondary = colors.get("secondary", "#ec4899")
    text_color = colors.get("text", "#0f172a")
    accent = colors.get("accent", "#38bdf8")

    navbar = page_tree.get("navbar", {})
    hero = page_tree.get("hero", {})
    about = page_tree.get("about", {})
    services = page_tree.get("services", {})
    features = page_tree.get("features", {})
    faq = page_tree.get("faq", {})
    testimonials = page_tree.get("testimonials", {})
    cta = page_tree.get("cta", {})
    contact = page_tree.get("contact", {})
    footer = page_tree.get("footer", {})

    css_content = f"""/* Generated by BuildMyWebsiteAI Studio - https://buildmywebsiteai.ai */
:root {{
  --bg-color: {bg};
  --surface-color: {surface};
  --primary-color: {primary};
  --secondary-color: {secondary};
  --text-color: {text_color};
  --accent-color: {accent};
  --font-family: 'Inter', system-ui, -apple-system, sans-serif;
}}

* {{ box-sizing: border-box; margin: 0; padding: 0; }}
html {{ scroll-behavior: smooth; }}
body {{ background-color: var(--bg-color); color: var(--text-color); font-family: var(--font-family); line-height: 1.6; overflow-x: hidden; }}
a {{ color: inherit; text-decoration: none; }}
.container {{ max-width: 1200px; margin: 0 auto; padding: 0 20px; width: 100%; }}

header {{ position: fixed; top: 0; left: 0; right: 0; z-index: 100; background: rgba(255, 255, 255, 0.95); backdrop-filter: blur(16px); border-bottom: 1px solid rgba(0, 0, 0, 0.08); padding: 14px 0; }}
.nav-wrap {{ display: flex; justify-content: space-between; align-items: center; position: relative; }}
.logo-wrap {{ display: flex; align-items: center; gap: 10px; font-weight: 800; font-size: 20px; color: var(--primary-color); }}
.logo-img {{ height: 34px; width: 34px; object-fit: contain; border-radius: 8px; }}
.nav-links {{ display: flex; gap: 24px; list-style: none; align-items: center; }}
.nav-links a:hover {{ color: var(--accent-color); transition: color 0.2s ease; }}
.btn-primary {{ background: linear-gradient(135deg, var(--primary-color), var(--secondary-color)); color: #fff; padding: 10px 24px; border-radius: 9999px; font-weight: 600; display: inline-block; border: none; cursor: pointer; box-shadow: 0 10px 25px -5px rgba(6, 182, 212, 0.4); transition: transform 0.2s ease; text-align: center; }}
.btn-primary:hover {{ transform: scale(1.04); }}

.mobile-toggle {{ display: none; background: transparent; border: 1px solid rgba(0, 0, 0, 0.15); border-radius: 8px; padding: 6px 10px; font-size: 18px; cursor: pointer; color: var(--text-color); }}

.hero-section {{ padding: 120px 0 60px; text-align: center; scroll-margin-top: 80px; }}
.badge {{ display: inline-block; background: rgba(6, 182, 212, 0.1); border: 1px solid var(--primary-color); color: var(--primary-color); padding: 6px 16px; border-radius: 9999px; font-size: 13px; font-weight: 600; margin-bottom: 20px; max-width: 100%; word-break: break-word; }}
.hero-title {{ font-size: 42px; font-weight: 900; margin-bottom: 20px; line-height: 1.2; color: var(--text-color); }}
.hero-subtitle {{ font-size: 17px; color: rgba(15, 23, 42, 0.75); max-width: 700px; margin: 0 auto 30px; line-height: 1.6; }}
.hero-img {{ width: 100%; max-width: 900px; height: auto; max-height: 480px; object-fit: cover; border-radius: 16px; margin-top: 30px; border: 1px solid rgba(0, 0, 0, 0.1); box-shadow: 0 20px 40px -10px rgba(0, 0, 0, 0.15); }}

.section {{ padding: 60px 0; scroll-margin-top: 80px; }}
.section-alt {{ padding: 60px 0; background: var(--surface-color); scroll-margin-top: 80px; }}
.section-header {{ text-align: center; margin-bottom: 40px; }}
.section-title {{ font-size: 32px; font-weight: 800; margin-bottom: 12px; }}
.section-subtitle {{ font-size: 15px; color: rgba(15, 23, 42, 0.7); max-width: 600px; margin: 0 auto; }}

.grid-3 {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 24px; }}
.grid-4 {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 20px; }}
.card {{ background: rgba(255, 255, 255, 0.95); border: 1px solid rgba(0, 0, 0, 0.08); border-radius: 16px; padding: 24px; transition: transform 0.3s ease, box-shadow 0.3s ease; }}
.card:hover {{ transform: translateY(-4px); box-shadow: 0 15px 30px rgba(0,0,0,0.08); }}

footer {{ background: #090d16; color: #94a3b8; padding: 40px 0 20px; text-align: center; font-size: 14px; margin-top: 40px; }}
footer a {{ color: var(--accent-color); }}

/* Full Mobile Viewport Responsiveness */
@media (max-width: 768px) {{
  .container {{ padding: 0 16px; }}
  .mobile-toggle {{ display: block; }}
  .nav-links {{ display: none; position: absolute; top: 100%; left: 0; right: 0; background: #ffffff; flex-direction: column; padding: 20px; gap: 16px; border-bottom: 1px solid rgba(0,0,0,0.1); box-shadow: 0 20px 25px -5px rgba(0,0,0,0.1); text-align: left; }}
  .nav-links.active {{ display: flex; }}
  .hero-section {{ padding: 100px 0 40px; }}
  .hero-title {{ font-size: 26px !important; line-height: 1.25; }}
  .hero-subtitle {{ font-size: 14px !important; padding: 0 8px; }}
  .hero-img {{ max-height: 260px !important; margin-top: 20px; }}
  .section-title {{ font-size: 24px !important; }}
  .grid-3, .grid-4 {{ grid-template-columns: 1fr !important; gap: 16px !important; }}
  .btn-primary {{ width: 100%; text-align: center; display: block; }}
}}
"""

    def build_page_html(page_name: str, p_data: Dict[str, Any]) -> str:
        p_hero = p_data.get("hero", hero)
        p_about = p_data.get("about") if website_type == "multi" else page_tree.get("about", about)
        p_services = p_data.get("services") if website_type == "multi" else page_tree.get("services", services)
        p_features = p_data.get("features") if website_type == "multi" else page_tree.get("features", features)
        p_faq = p_data.get("faq") if website_type == "multi" else page_tree.get("faq", faq)
        p_testimonials = p_data.get("testimonials") if website_type == "multi" else page_tree.get("testimonials", testimonials)
        p_cta = p_data.get("cta") if website_type == "multi" else page_tree.get("cta", cta)
        p_footer = p_data.get("footer", footer)

        nav_items_html = "".join([f'<li><a href="{link.get("href")}">{link.get("label")}</a></li>' for link in navbar.get("links", [])])
        logo_img_html = f'<img src="{logo_url}" alt="Logo" class="logo-img">' if logo_url else ''

        # Build Section HTML snippets with AOS Scroll Animations & Mobile Compatibility
        hero_html = f"""
  <section id="home" class="hero-section" data-aos="fade-down">
    <div class="container">
      {f'<span class="badge">{p_hero.get("badge")}</span>' if p_hero.get("badge") else ''}
      <h1 class="hero-title">{p_hero.get("headline", brand_name)}</h1>
      <p class="hero-subtitle">{p_hero.get("subheadline", "")}</p>
      <div>
        <a href="#services" class="btn-primary">{p_hero.get("primary_cta", "Explore Services")}</a>
      </div>
      {f'<img src="{p_hero.get("hero_image")}" alt="Hero" class="hero-img" data-aos="zoom-in" data-aos-delay="200">' if p_hero.get("hero_image") else ''}
    </div>
  </section>"""

        about_html = ""
        if p_about and p_about.get("paragraphs"):
            paragraphs_html = "".join([f'<p style="margin-bottom: 12px; font-size: 14px; line-height: 1.7;">{p}</p>' for p in p_about.get("paragraphs", [])])
            about_html = f"""
  <section id="about" class="section-alt" data-aos="fade-up">
    <div class="container">
      <div class="section-header">
        <span class="badge">{p_about.get("section_badge", "About Us")}</span>
        <h2 class="section-title">{p_about.get("section_title", f"About {brand_name}")}</h2>
      </div>
      <div style="max-width: 800px; margin: 0 auto;">
        {paragraphs_html}
      </div>
    </div>
  </section>"""

        services_html = ""
        if p_services and p_services.get("items"):
            s_cards = "".join([f"""
        <div class="card" data-aos="fade-up">
          <h3 style="font-size: 18px; font-weight: 700; margin-bottom: 10px; color: var(--primary-color);">{item.get("title")}</h3>
          <p style="font-size: 13px; color: rgba(15, 23, 42, 0.7);">{item.get("description")}</p>
        </div>""" for item in p_services.get("items", [])])
            services_html = f"""
  <section id="services" class="section" data-aos="fade-up">
    <div class="container">
      <div class="section-header">
        <span class="badge">{p_services.get("section_badge", "Services")}</span>
        <h2 class="section-title">{p_services.get("section_title", "Our Services")}</h2>
        <p class="section-subtitle">{p_services.get("section_subtitle", "")}</p>
      </div>
      <div class="grid-3">
        {s_cards}
      </div>
    </div>
  </section>"""

        features_html = ""
        if p_features and p_features.get("items"):
            f_cards = "".join([f"""
        <div class="card" data-aos="fade-up">
          <h3 style="font-size: 18px; font-weight: 700; margin-bottom: 8px;">{item.get("title")}</h3>
          <p style="font-size: 13px; color: rgba(15, 23, 42, 0.7);">{item.get("description")}</p>
        </div>""" for item in p_features.get("items", [])])
            features_html = f"""
  <section id="features" class="section-alt" data-aos="fade-up">
    <div class="container">
      <div class="section-header">
        <span class="badge">{p_features.get("section_badge", "Capabilities")}</span>
        <h2 class="section-title">{p_features.get("section_title", "Why Choose Us")}</h2>
        <p class="section-subtitle">{p_features.get("section_subtitle", "")}</p>
      </div>
      <div class="grid-3">
        {f_cards}
      </div>
    </div>
  </section>"""

        faq_html = ""
        if p_faq and p_faq.get("items"):
            faq_items = "".join([f"""
        <div class="card" style="margin-bottom: 12px; padding: 20px;" data-aos="fade-up">
          <h4 style="font-size: 15px; font-weight: 700; margin-bottom: 6px;">{item.get("question")}</h4>
          <p style="font-size: 13px; color: rgba(15, 23, 42, 0.7);">{item.get("answer")}</p>
        </div>""" for item in p_faq.get("items", [])])
            faq_html = f"""
  <section id="faq" class="section" data-aos="fade-up">
    <div class="container" style="max-width: 800px;">
      <div class="section-header">
        <h2 class="section-title">{p_faq.get("section_title", "Frequently Asked Questions")}</h2>
      </div>
      {faq_items}
    </div>
  </section>"""

        testimonials_html = ""
        if p_testimonials and p_testimonials.get("items"):
            t_cards = "".join([f"""
        <div class="card" data-aos="fade-up">
          <p style="font-size: 13px; font-style: italic; margin-bottom: 16px;">"{item.get("quote")}"</p>
          <div style="font-weight: 700; font-size: 14px; color: var(--primary-color);">{item.get("name")}</div>
          <div style="font-size: 12px; color: rgba(15, 23, 42, 0.6);">{item.get("role")}</div>
        </div>""" for item in p_testimonials.get("items", [])])
            testimonials_html = f"""
  <section id="testimonials" class="section-alt" data-aos="fade-up">
    <div class="container">
      <div class="section-header">
        <h2 class="section-title">{p_testimonials.get("section_title", "What Clients Say")}</h2>
      </div>
      <div class="grid-3">
        {t_cards}
      </div>
    </div>
  </section>"""

        cta_html = f"""
  <section id="contact" class="section" style="background: linear-gradient(135deg, var(--surface-color), var(--bg-color)); text-align: center;" data-aos="zoom-in">
    <div class="container" style="max-width: 700px;">
      <h2 class="section-title">{p_cta.get("headline", f"Ready to Connect with {brand_name}?")}</h2>
      <p class="hero-subtitle">{p_cta.get("subheadline", "Reach out today and our dedicated team will respond promptly.")}</p>
      <a href="mailto:{p_footer.get("contact_email", "info@example.com")}" class="btn-primary" style="margin-top: 10px;">{p_cta.get("button_text", "Contact Us Now")}</a>
    </div>
  </section>"""

        footer_html = f"""
  <footer>
    <div class="container">
      <p style="font-weight: 700; margin-bottom: 6px; color: #fff;">{p_footer.get("brand", brand_name)}</p>
      <p style="margin-bottom: 16px;">{p_footer.get("copyright", f"© 2026 {brand_name}. All rights reserved.")}</p>
      <p style="font-size: 12px; opacity: 0.6;">{p_footer.get("credit", "Website built by BuildMyWebsiteAI")}</p>
    </div>
  </footer>"""

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <title>{brand_name} - {page_name}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet">
  <!-- AOS Animate On Scroll Library CDN -->
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header>
    <div class="container">
      <div class="nav-wrap">
        <div class="logo-wrap">
          {logo_img_html}
          <span>{brand_name}</span>
        </div>
        <button class="mobile-toggle" id="mobile-toggle" aria-label="Toggle Menu">☰</button>
        <ul class="nav-links" id="nav-links">
          {nav_items_html}
          <li><a href="#contact" class="btn-primary" style="padding: 6px 18px; font-size: 13px;">Get In Touch</a></li>
        </ul>
      </div>
    </div>
  </header>

  {hero_html}
  {about_html}
  {services_html}
  {features_html}
  {faq_html}
  {testimonials_html}
  {cta_html}
  {footer_html}

  <!-- AOS Animate On Scroll JS Script -->
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init({{ duration: 800, once: true }});
    // Mobile Hamburger Navigation Toggle Script
    document.getElementById('mobile-toggle').addEventListener('click', function() {{
      document.getElementById('nav-links').classList.toggle('active');
    }});
  </script>
</body>
</html>"""

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        zip_file.writestr("style.css", css_content)

        if website_type == "multi":
            for p_name in selected_pages:
                file_name = "index.html" if p_name == "Home" else f"{p_name.lower().replace(' ', '_')}.html"
                p_data = pages_dict.get(p_name, {})
                zip_file.writestr(file_name, build_page_html(p_name, p_data))
        else:
            zip_file.writestr("index.html", build_page_html("Home", page_tree))

    zip_buffer.seek(0)
    return zip_buffer
